name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Obfuscate JavaScript files
        run: npm run obfuscate

      - name: Replace original JS with obfuscated JS
        run: |
          rm -rf src/
          mv dist/ src/

      - name: Commit and push obfuscated files
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add src/
          git commit -m "Replace JS files with obfuscated versions"
          git push origin main
